name: Build and Secret Scanning Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  secret-scanning:
    name: Secret Scanning (Gitleaks)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Gitleaks with baseline
        run: |
          docker run --rm \
            -v "${{ github.workspace }}:/code" \
            zricethezav/gitleaks:latest \
            detect --source=/code \
                   --baseline-path=/code/leaks-baseline.json \
                   --report-format=sarif \
                   --report-path=/code/gitleaks-report.sarif \
                   --verbose

  build:
    name: Build Project
    runs-on: ubuntu-latest
    needs: secret-scanning

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run build
        run: npm run build